### PR TITLE
Adding a pipeline example of encryption-decryption execution in README.md

### LINKED ISSUE #3: Attaching the output image
Run this encryption and decryption algorithm and attach its output image in a README.md file.

### PR DESCRIPTION
**Pull request by rrbarioni**
Hello!

I am putting a example of a encryption-decryption pipeline into README.md.
Contact me if you have any questions.

resolve #3

### CODE REVIEW

**Comment by codeShaurya** [comment]
That looks great but there is a merge conflict.
solve this merge conflict and submit another PR.

**Comment by rrbarioni** [comment]
Oh, my bad, I didn't see that. Now it's done =)

**Comment by codeShaurya** [comment]
and order should be:
-Original image
-Permuted image 
-Encrypted Image (Permuted and diffused Image)
-Decrypted Permuted Image
-Original Image
Image's order is fine, just change the caption of images

**Comment by rrbarioni** [comment]
All right, now it's updated.

**Pull request merged**
